language: python
python:
- '3.6'
script:
- bash ./deploy-to-gh-pages.sh
env:
  global:
  - GITHUB_REPO: "Non-Contradiction/Introduction-to-SAS"
  - GITHUB_USER: "Non-Contradiction"
  - secure: "zt0hqN3fSXfSU+w2c25Tb05nlD8e+9wF6rU47i6mAXwLYq6i0u7cMVwtVC6DTPaa++1HcXSUy7uqcmw3REsVsj+OhhCL+esp6eR8JcAuauueAD75acxENNWeTgmiYOjHY3MlAPOqz7c5IQ4u1u38ViQOVd9qz4MdLHxprrtch72yJETFGhzGPtxc/UYqlMe7820uHLubZIxYj+pIRdC9VNWuTohCaoY8oUWNqAB+djcpfCmtKeVptEqByP0hSuD9x0gbYilRbegSLDpFPetCI1bMMq/tg8iaYGEW0jIluUMd4a5CexBs83TG4Ntan1W32+v5idIEsXdzsAXSzPiP5jXUyCkswRHBrnpaWkHEsiDEUcPbj4ZQERWfrtnSDlP1t0OdAyFi6va7tQ8JGZsML0rAcLXAQcNioHOLQZTUhsjUpVFTyL5EdQisCddr7obbMlhisyIBkw6klNgmjT1PyfwfXvRx9wjxUqJNoJT7d+rh3XyETvxOPh8hcNTTzUudjrjqn9LH7BlP8jYkJBQdzMejKfFyzYQfUd2fSHP61U1+2PrQUDRnHOCMrY302h3UFYYP3iva0ZYknDHPqJJV8grlXSjxsK1trFToDjvnckWw0avzqC33jGbPBBL0hfpl22NrOQxhJNpdii8/5GL/my3iDCYsNd+D3OpZljwUgLI="
